version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mynetwork

  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
